name: 哈喽短视频

on:
  workflow_dispatch:
  schedule:
     - cron: '15 3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        HL_URL: ${{ secrets.HL_URL }}
        HL_HD: ${{ secrets.HL_HD }}	

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/YiYu.git ~/js
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.HL_URL
        run: |
          cd ~/js
          git checkout FeiZao
          npm install
      - name: '运行 【哈喽短视频】'
        if: env.HL_URL
        run: |
          cd ~/js
          node Taskhldsp.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
